tiny-firmware/README.md, tiny-firmware/prepare-sky-hw.sh
@mpsido This PR adds a file named `prepare-sky-hw.sh` that allows to automatically create the configuration file described in https://github.com/skycoin/hardware-wallet/tree/master/tiny-firmware#configure-your-usb-module. The idea is that end users can use that file to configure the system easily, instead of having to manually create/modify system files.
In my tests I saw that only the two configuration lines below `## 313a:0001` are necessary, but, just in case, the created file is the same as the one described in the README. If the other lines are not necessary, it would be good to delete them.
The README was updated.
=> [Hardware-Wallet]: Create the Linux configuration file automatically

.gitignore, tiny-firmware/README.md
Fixes #48 
Changes:
- GCC EABI install instructions on MacOS with homebrew
- GCC EABI install instructions on Ubuntu>=16.04 using apt
Does this change need to be mentioned in CHANGELOG?
No
=> fixes #48 - MacOS dev setup

Makefile, skycoin-api/skycoin_crypto.h, tiny-firmware/Makefile, tiny-firmware/Makefile.include, tiny-firmware/firmware/droplet.c, tiny-firmware/firmware/droplet.h, tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/skyparams.h, tiny-firmware/firmware/test_droplet.c, tiny-firmware/firmware/test_droplet.h, tiny-firmware/firmware/test_fsm.c, tiny-firmware/firmware/test_fsm.h, tiny-firmware/firmware/test_main.c, tiny-firmware/protob/types.proto
Fixes #78
Fixes #91 
Changes:
- Change byte size of coins and hours `uint32_t` => `uint64_t`
- Function to render integer coin values as requested in #78 (no conversion to float)
- Include path properly set to run `make test` on osx and linux platforms
no
yes
Tested with check. Test code refactored to have a `main()` function and a separate mechanism to add test cases .
Related to skycoin/hardware-wallet-js#56 and skycoin/hardware-wallet-go#35
=> [firmware] fixes #78 #91 - Coin fractions in Skywallet display

tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/test_fsm.c
Fixes #119 
Changes:
- Check that word count in `GenerateMnemonic` message is either 12 or 24 . 
Known issues
Other valid values may be added later .
no
yes
Test case added in `test_fsm.c`.
=> [firmware] fixes #119 - Validate mnemonic count in firmware 

README.md
Refs #64
Changes:
- Versioning scheme for firmware, bootloader, and combined release
- Updates in `protob` submodule at release time
no
no
=> refs #64 - Project versionning scheme

tiny-firmware/firmware/fsm.c
Fixes #135 
Changes:
- Disabled the confirmation for set the language when an empty string is provided.
no
yes
=> [wallet] refs #135 - Disable confirmation if no language provided

.gitignore, tiny-firmware/emulator/oled.c, tiny-firmware/emulator/udp.c
Fixes #147 
Changes:
- Changes in the properties to generate the windows, changing the title of TREZOR=>SkyWallet
no
no
=> Fixes #147 Change name windows to Skywallet

tiny-firmware/firmware/droplet.c, tiny-firmware/firmware/droplet.h, tiny-firmware/firmware/test_droplet.c
Fixes #111
Changes:
- Correct text when coins are 1.5
- Verify work for different fractions of coins
no
yes
Examples
4.9023 SKY = 4902300 droplets
9.703  SKY = 9703000 droplets
3.23  SKY = 3230000 droplets
2.01  SKY = 2010000 droplets
1.5  SKY = 1500000 droplets
0.1  SKY = 100000 droplets
=> fixes #111 Print 1.5 coins correctly

tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/test_fsm.c
Fixes #146
Changes:
- Do not delete(restore to a default value) label if it is not have a value in applySettings.
no
yes
=> Delete label by accident ref #146

README.md, tiny-firmware/bootloader/bootloader.c, tiny-firmware/emulator/emulator.h, tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/fsm_impl.h, tiny-firmware/firmware/layout2.c, tiny-firmware/firmware/test_fsm.c
refs #151 
Changes:
- Only sign transaction inputs with address `index` field set
- Consistent error messages in `ApplySettings` message handler
no
yes , related to PR skycoin/hardware-wallet-protob#37 
yes
... needs tests ...
=> refs #151 - Improve transaction input signing and apply settings

tiny-firmware/firmware/error.h, tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/fsm_impl.h, tiny-firmware/firmware/test_fsm.c
refs #151 
Changes:
- Failure message for invalid language values is `Invaid argument`
- Failure message for no settings is `No settings provided`
no
no
yes
these are not captured on `fsm_impl.c` since it's beyond the scope of `*Impl` message handlers.
=> refs #151 Differentate failure messages in ApplySettings

tiny-firmware/firmware/test_fsm.c
Fixes #171
Changes:
- Ensure number of address is positive while testing Skycoin address generation
no
no
yes
happened in tests
=> refs #171 Boundary checks for address test cases

tiny-firmware/bootloader/usb.c, tiny-firmware/firmware/usb.c
Fixes #194 
Changes:
- `SKYCOIN` chnaged to `SKYWALLET` in product string.
no
no
no
=> product string from SKYCOIN to Skywallet

tiny-firmware/Makefile, tiny-firmware/firmware/pinmatrix.c, tiny-firmware/firmware/pinmatrix.h, tiny-firmware/firmware/protect.c, tiny-firmware/firmware/test_fsm.c, tiny-firmware/firmware/test_main.c, tiny-firmware/firmware/test_protect.c, tiny-firmware/firmware/test_protect.h
Fixes #188 
Changes:
- Cut pin code if invalid char found during matrix translation 
no
no
yes
see `test_protect.{c,h}`
=> fixes #188 - Fix pin codes with bad chars and equal length pass the pin check

CHANGELOG.md, tiny-firmware/firmware/main.c, tiny-firmware/firmware/storage.c, tiny-firmware/memory.h, tiny-firmware/serialno.c
Fixes #202
closes #100
closes #131 (@stdevIvr these number are the device uuid, coming physical device id with this pr, a random one in emulator, so can be different in emulator)
Changes:
- Read uuid from physical device.
- Please do not miss [this change](https://github.com/skycoin/hardware-wallet/pull/203/commits/a094382a48bc4f0dba3d5e690b3d042030a9fe97). ref #100 
yes
Requires changes in protobuf specs?
no
no
=> Read device UUID ref #202

Makefile, ci-scripts/version.sh
Fixes #217 
Changes:
- Do not read version from git SHA1 due to [failures](https://travis-ci.org/simelo/skycoin-hardware-wallet-js/jobs/530050283#L2340-L2357) . 
no
no
no
=> fixes #217 Fix bug determining firmware and bootloader version number

tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/fsm.h, tiny-firmware/firmware/fsm_impl.h, tiny-firmware/firmware/messages.c, tiny-firmware/firmware/protect.c, tiny-firmware/firmware/recovery.c, tiny-firmware/firmware/reset.c
Fixes #228 
Changes:	
- Implement msg_type in success and failure responses
- Do not navigate to home screen after merging external entropy (beaks ongoing op)
yes
yes
No visible changes in test suite since message handler signatures did not change. Nonetheless will be tested in hw-js library
=> [firmware] fixes #228 - Include type of message success / failure is sent for

README.md
Fixes #245 
Changes:	
- Document binary release filenames in version policies section of main README
no
no
=> fixes #245 - Release binary filenames

tiny-firmware/firmware/error.h, tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/test_fsm.c
Fixes #251
Changes:	
- Fix error notification from `fsm_msgSkycoinCheckMessageSignature`.
- Refactor `test_msgSkycoinCheckMessageSignatureOk` test.
no	
yes
=> Check message signature err msg ref #251

tiny-firmware/firmware/fsm_impl.c
Fixes #271
Changes:	
- Null signatures in `msgTransactionSignImpl` if input index not set
no	
yes
=> [firmware] fixes #271 - Do not return empty strings for sigs

tiny-firmware/firmware/storage.c, tiny-firmware/firmware/test_fsm.c
Fixes #243 
Changes:	
- Ignore empty passphrase
no
yes , added in `fsm_impl.c`
=> [firmware] fixes #243 - Ignore empty passphrase

Makefile, tiny-firmware/bootloader/Makefile
Fixes #291	
Changes:	
-Creating different object files for firmware or bootloader.
no	
no
Additional info:
Some files are shared for bootloader and firmware for example [`setup.c` for firmware](https://github.com/skycoin/hardware-wallet/blob/12968889ca8d5e96201e2defeb92e2c137911f73/tiny-firmware/Makefile#L7) and [`setup.c` for bootloader](https://github.com/skycoin/hardware-wallet/blob/12968889ca8d5e96201e2defeb92e2c137911f73/tiny-firmware/bootloader/Makefile#L5). Those files are build with different flags for example if you build a firmware and then a bootloader, the result bootloader is too big because some files was no build with `-Os` (optimize for size), some similar strange behavior occur if you build the …
=> fix full-firmware build fixes #291

tiny-firmware/firmware/fsm_impl.c
Fixes #244 
Changes:	
- Use current label in `recovery_init` for not remove it if empty
no	
yes , but not possible now .
=> [firmware] fixes #244 - Fix label erased after device recovery

tiny-firmware/firmware/fsm.c
Fixes #310 
Changes:	
- Add `FirmwarePanic` and `default` case in `sendFailure` function 
no	
no
=> add missing send failure case

tiny-firmware/firmware/fsm_impl.c
Fixes #313 
Changes:	
- set buffer size for signature and 	
no	
no
=> fix buffer size for CheckMessageSignature ref #313

tiny-firmware/bootloader/bootloader.c, tiny-firmware/bootloader/usb.c, tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/main.c, tiny-firmware/memory.c, tiny-firmware/memory.h
Fixes #286 
Changes:	
- Implement `memory_rdp_level()`
- Remove `extern rdp_level` and `set_up_rdp_level()`
no	
yes | no	
Impossible to test if not have one device
=> [firmware] [bootloader] fixes #286 - Change names of RDP level

trng-test/Makefile
Fixes #324
Changes:	
- Run dieharder in resolve ambiguity mode([`-k 2 -Y 1`](https://www.systutorials.com/docs/linux/man/1-dieharder/)).
no	
no
=> Run dieharder in resolve ambiguity mode ref #324

tiny-firmware/firmware/fsm.c, tiny-firmware/firmware/fsm_impl.c, tiny-firmware/firmware/reset.c, tiny-firmware/firmware/reset.h
Fixes #321
Changes:	
- Change `reset_backup` signature to return an error.
- Check `reset_backup` ret value and go to home screen if non ok.
- Do not send cancel response from fsm layer.
no	
[later](https://github.com/skycoin/hardware-wallet/issues/178)
=> Fix cancel backup ref #321

Makefile, tiny-firmware/Makefile.include, tiny-firmware/firmware/main.c
Fixes #	
Changes:	
-Now it is possible to debug project using OpenOCD. Also added semihosting support. Semihosting is feature, which alows you to redirect output from the "printf()" function into debugger console. To allow semihosting, set SEMIHOSTING=1
yes | no	
yes | no	
=> Added OpenOCD Debug support and Semihosting
