- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .gitignore
Fixes #55 
Changes:
- Templates for bug report, feature, PR
Needs to be mentioned in CHANGELOG
No
> [ci] fixes #55 - Github templates

- tiny-firmware/emulator/oled.c
Fixes #73 
Changes:
- Fix licensing headers after #73 
no
no
> fixes #73 - Licensing revised

- CHANGELOG.md
- tiny-firmware/firmware/fsm.c
Fixes #124 
Changes:
- Added a function that verifies the language provided by the user in `applySettings` and set it to `English` if empty
yes
yes
> [firmware] fixes #124 - Verify language and set to English if empty

- .github/pull_request_template.md
Fixes #143
Changes:
- Mention protobuff changes related to PR (if any) while creating it 
no
no
> fixes #143 - Protobuff changes related to PR (if any)

- .github/ISSUE_TEMPLATE/blank.md
Fixes #143 
Changes:
- Blank issue template
no
no
> fixes  #143 - Blank issue template

- tiny-firmware/bootloader/bootloader.c
- tiny-firmware/bootloader/usb.c
- tiny-firmware/firmware/skywallet.c
Fixes #176 
Fixes #83 
Fixes #134 
Changes:
- Update firmware message in order to show a message according to the size of the screen.
yes
> Fixes #176 Update firmware message

- tiny-firmware/firmware/main.c
- tiny-firmware/firmware/storage.c
- tiny-firmware/firmware/storage.h
Fixes #202 
Changes:
- Multiple fixes after review in https://github.com/skycoin/hardware-wallet/pull/203
no
no
no
> Device UUID fixes ref #202

- tiny-firmware/firmware/fsm.c
- tiny-firmware/firmware/fsm_impl.c
Fixes #220 
Changes:
- Fix bug in msg sequence
no
no
no
> Fix an extra message send in fsm_msgSkycoinSignMessage ref #220

- .travis.yml
- CHANGELOG.md
Fixes #210 
Changes:
- Instructions to deploy from Travis to to S3 bucket.
yes
no
no
> AWS deploy ref #210

- tiny-firmware/firmware/fsm.c
- tiny-firmware/firmware/fsm_impl.c
Fixes #219
Changes:
- Remove not useful screen messages
no
Requires changes in protobuf specs?
no
no
> Fix bug in skycoin sign message ref #219

- .travis.yml
- tiny-firmware/firmware/fsm.c
- tiny-firmware/firmware/fsm_impl.c
Fixes #217
Changes:
- Fix bug in sign message.
- Fix syntax error in Travis script
no
Requires changes in protobuf specs?
no
no
> Bug in sign message ref #217

- README.md
Copied the responsible disclosure section from skycoin/skycoin as @gz-c  said we should use the identical process as with the core repo.
Fixes #	
Changes:	
-	
yes | no	
yes | no	
> Add Responsible Disclosure section

- FAQ.md
- README.md
Fixes #235
Changes:	
- Submodule initialization before running any command
- Notes in FAQ to always run Python3 
no	
no
> fixes #235 - Improve getting started Instructions

- .travis.yml
Fixes #211
Changes:	
- Do not deploy to Github Releases
no
no
> [ci] fixes #211 - Do not deploy to Github Releases

- FAQ.md
- tiny-firmware/firmware/fsm.c
Fixes #257
Changes:	
- fix fsm_msgSkycoinSignMessage for wiped device
- fix in typo for FAQ
no	
no	
> fix fsm_msgSkycoinSignMessage for wiped device ref #257

- .travis.yml
- README.md
- ci-scripts/install-linux.sh
Changes:
- Update travis to `xenial`
- Add project banner to readme
no
no
no
> update to xenial and add banner

- .travis.yml
- Makefile
Fixes #269
Changes:	
- Deploy in tags
no
no
> [WIP] deploy on tags ref #269

- Makefile
- skycoin-api/Makefile
Fixes #267
Changes:	
- Just run skycoin-api python test
no	
no
> run pytest from skycoin-api fixes #267

- FAQ.md
Fixes #	
Changes:	
- Added FAQ section for entropy salt sources
yes | no	
no	
Comments about testing, should you have some
Read and give me advice
> Added FAQ section for entropy salt sources #298

- .travis.yml
Changes:	
- Update submodule to remote branch in travis 
no	
no
> update submodule to remote branch in travis

- tiny-firmware/firmware/test_fsm.c
Fixes #306 
Fixes #308 
Changes:	
- improve fsm tests	
no	
no
> fsm test, make use of 24 words seed as well ref #306

- tiny-firmware/firmware/fsm_impl.c
Fixes #110
Changes:	
- Fix usage of `fsm_getKeyPairAtIndex`
- Fix usage of `skycoin_address_from_pubkey`
no	
no
> fix usage of skycoin_address_from_pubkey ref #110

- tiny-firmware/firmware/bootloader_integrity.c
- tiny-firmware/firmware/bootloader_integrity.h
Changes:	
- Now firmware checks hash for different bootloader's hashes
no	
no	
> Added bootloader's hash list
